include("${PROJECT_SOURCE_DIR}/cmake/assets.cmake")

set(TEST_ARCHIVE_DIR "${PROJECT_BINARY_DIR}/test-downloads")
set(TEST_ARCHIVE_PATH "${TEST_ARCHIVE_DIR}/data.tar.gz")
set(TEST_EXTRACT_DIR "${PROJECT_BINARY_DIR}/data.extract")
set(TEST_DATA_DIR "${PROJECT_BINARY_DIR}/data")

if(NOT DEFINED OSU_TEST_DATA_URL OR OSU_TEST_DATA_URL STREQUAL "")
    message(FATAL_ERROR "OSU_TEST_DATA_URL is not set")
endif()

file(MAKE_DIRECTORY "${TEST_ARCHIVE_DIR}")

file(DOWNLOAD
    "${OSU_TEST_DATA_URL}"
    "${TEST_ARCHIVE_PATH}"
    SHOW_PROGRESS
    STATUS DOWNLOAD_STATUS
    TLS_VERIFY ON
)

list(GET DOWNLOAD_STATUS 0 DOWNLOAD_STATUS_CODE)
list(GET DOWNLOAD_STATUS 1 DOWNLOAD_STATUS_MESSAGE)

if(NOT DOWNLOAD_STATUS_CODE EQUAL 0)
    message(FATAL_ERROR "failed to download test data: ${DOWNLOAD_STATUS_MESSAGE}")
endif()

file(REMOVE_RECURSE "${TEST_EXTRACT_DIR}" "${TEST_DATA_DIR}")
file(MAKE_DIRECTORY "${TEST_EXTRACT_DIR}")

execute_process(
    COMMAND "${CMAKE_COMMAND}" -E tar xzf "${TEST_ARCHIVE_PATH}"
    WORKING_DIRECTORY "${TEST_EXTRACT_DIR}"
    RESULT_VARIABLE EXTRACT_RESULT
)

if(NOT EXTRACT_RESULT EQUAL 0)
    message(FATAL_ERROR "failed to extract test data archive")
endif()

set(TEST_DATA_SOURCE_DIR "${TEST_EXTRACT_DIR}")

if(EXISTS "${TEST_EXTRACT_DIR}/tests/.data")
    set(TEST_DATA_SOURCE_DIR "${TEST_EXTRACT_DIR}/tests/.data")
elseif(EXISTS "${TEST_EXTRACT_DIR}/.data")
    set(TEST_DATA_SOURCE_DIR "${TEST_EXTRACT_DIR}/.data")
elseif(EXISTS "${TEST_EXTRACT_DIR}/data")
    set(TEST_DATA_SOURCE_DIR "${TEST_EXTRACT_DIR}/data")
endif()

file(RENAME "${TEST_DATA_SOURCE_DIR}" "${TEST_DATA_DIR}")
