singleQuote: false
semi: true
printWidth: 150
trailingComma: none
useTabs: true
bracketSpacing: true
tabWidth: 2
plugins:
  - prettier-plugin-svelte
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
