name: build osu-stuff

on:
  create:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev build-essential
          mkdir -p /usr/local/bin
          curl -L https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -o /usr/local/bin/appimagetool
          chmod +x /usr/local/bin/appimagetool
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run make
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: out/*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: build app
        run: npm run make
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/*

  create-release:
    needs:
      - build-linux
      # - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: create draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          # artifacts/windows-build/*
          files: |
            artifacts/linux-build/*
