
# TODO: a way to generate the release information so i can remove the draft


name: build osu-stuff

on:
  create:
    tags:
      - 'v*'


jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: nodejs setup
        uses: actions/setup-node@v2
        with:
          node-version: 20
      # prob not needed
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev build-essential
          mkdir -p /usr/local/bin
          curl -L https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -o /usr/local/bin/appimagetool
          chmod +x /usr/local/bin/appimagetool
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            dist/*.AppImage
            dist/*.deb

  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: nodejs setup
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: build app
        run: npm run build
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist/*.exe

  create-release:
    needs: 
      - build-linux
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: build
          path: artifacts/build
      - name: create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            ./artifacts/build/*.AppImage
            ./artifacts/build/*.deb
            ./artifacts/build/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}
