name: test

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        env:
            SCCACHE_GHA_ENABLED: "true"

        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: setup sccache
              if: runner.os != 'Windows'
              uses: mozilla-actions/sccache-action@v0.0.10

            - name: install cppcheck (windows)
              if: runner.os == 'Windows'
              run: |
                  choco install cppcheck --yes
                  echo "C:\Program Files\Cppcheck" >> $env:GITHUB_PATH

            - name: install system dependencies (ubuntu)
              if: runner.os == 'Linux'
              run: |
                sudo apt-get update
                sudo apt-get update && sudo apt-get install -y \
                build-essential cmake ninja-build libgl1-mesa-dev \
                libssl-dev libcurl4-openssl-dev libuv1-dev zlib1g-dev \
                libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxfixes-dev libxss-dev libwayland-dev libxkbcommon-dev \
                libegl1-mesa-dev libdecor-0-dev libxtst-dev \

            - name: setup msvc
              if: runner.os == 'Windows'
              uses: ilammy/msvc-dev-cmd@v1

            - name: setup env
              run: python ./ez init

            - name: configure
              run: python ./ez configure --type="debug"
              env:
               SCCACHE_GHA_ENABLED: "true"

            - name: test
              run: python ./ez test

            - name: sccache stats
              if: runner.os == 'Linux'
              run: sccache --show-stats
